version: "3"
services:
  # NGINX
  radar-nginx:
    image: nginx
    volumes:
      - ./radar-nginx:/etc/nginx/templates
    ports:
      - 9998:9998
    env_file: .env
    container_name: radar-nginx
    depends_on:
      - radar-api
      - radar-admin
      - radar-client
    restart: always
  ukrdc-import:
    # image: replace once image location known
    build: ./ukrdc-import
    ports:
      - 9998:9998
    env_file: .env
    container_name: radar-nginx
    depends_on:
      - radar-api
      - radar-admin
      - radar-client
    restart: always
