version: "3"
services:
  # Database
  db:
    build: ./radar-db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: radar-db

volumes:
  data:
