version: "3"
services:
  radar-api:
    build: ./radar
    ports:
      - "5000:5000"
    command: radar-api
    volumes:
      - ./radar/radar:/radar/radar
      - ./radar/migrations:/radar/migrations
    env_file:
      - .env
    container_name: radar-api
    depends_on:
      - db
  # Backend Admin
  radar-admin:
    build: ./radar
    ports:
      - "5002:5002"
    command: radar-admin
    volumes:
      - ./radar/radar:/radar/radar
    env_file:
      - .env
    container_name: radar-admin
    depends_on:
      - db
  # Frontend
  radar-client:
    build: ./radar-client
    ports:
      - "8080:8080"
    volumes:
      - ./radar-client/src:/app/src
    container_name: radar-client
    stdin_open: true
    tty: true
    depends_on:
      - radar-api
